### ISSUE TITLE
Multiword titles

### ISSUE THREAD

**Issue by DutchPete** [ranmaru22/obsidian-freelinks#1]
How does the plug-in handle multiword note titles? Or is that something yet to be introduced?

**Comment by ranmaru22** [comment]
The only issue that exists at the moment is if you have a multi word title and then another one that is a subset of that title. For example, one note is called "My Recipe List" and another one is called "Recipe". 

This would match either or the other, depending on which gets pulled out of the hashmap first (and b/c hashmaps aren't sorted, it can change).

Other than that it should handle multi word titles just fine as it's all hash keys and regular expressions under the hood.

**Comment by DutchPete** [comment]
OK, thanks for the feedback.
